[project]
name = "expensetracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Siddharth Mishra", email = "vanadium.io.509@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.128.8",
]

[project.scripts]
expensetracker = "expensetracker:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
