spring.application.name=expenses
spring.datasource.url=jdbc:postgresql://localhost:5432/expenses
spring.datasource.username=postgres
spring.datasource.password=devpass
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true